<h4>Members</h4>
<form action="/social/filter" id="randomInsert" method="post">
	<div>
		<input type="hidden" name="id" />
		<input type="text" class="form-control zoek" placeholder="Search by.." name="term"  />
		<select name="memberrow" class="form-control memberrow">
			<option value="username">Username</option>
			<option value="email">Email</option>
		</select>
		<input type="hidden" name="table" value="member">
		<input type="hidden" name="field" value="username">
		<input type="submit" class="btn " name="zoek" value="zoek" />
	</div>
</form>
<div class="widget">
	<div class="widget-head">
		<div class="pull-left">Members</div>
		<div class="widget-icons pull-right">
			<a href="#" class="wminimize"><i class="icon-chevron-up"></i></a> 
			<a href="#" class="wclose"><i class="icon-remove"></i></a>
		</div>  
		<div class="clearfix"></div>
	</div>
	<div class="widget-content">
		<table class="table table-striped table-bordered table-hover" id="table" style="width:100%">
		<tr><th>User Id</th><th>Username</th><th>Emailaddress</th><th>Group Role</th><tr>
			<?php foreach ($this->paginator as $member) : // <-- change here! ?>
				<tr>

					<td><?php echo '<a href="/profile/' . $member->user_id . '">' . $this->escapeHtml($member->user_id) .'</a>' ;?></td>
					<td><?php echo '<a href="/profile/' . $member->user_id . '">' . $this->escapeHtml($member->username) .'</a>' ;?></td>
					<td><?php echo '<a href="/profile/' . $member->user_id . '">' . $this->escapeHtml($member->email) .'</a>' ;?></td>
					<td><?php echo '<a href="/profile/' . $member->user_id . '">' . $this->escapeHtml($member->group_role) .'</a>' ;?></td>

				</tr>
			<?php endforeach; ?>
		</table>
		<div class="widget-foot">
			<?php
			
			echo $this->paginationControl(
				// the paginator object
				$this->paginator,
				// the scrolling style; see http://zf2.readthedocs.org/en/release-2.1.4/modules/zend.paginator.usage.html#rendering-pages-with-view-scripts
				'sliding',
				// the partial to use to render the control
				array('partial/paginator.phtml', 'Member'),
				// the route to link to when a user clicks a control link
				array(
					'route' => 'social'
					)
					);
			
					?> 
				</div>
			</div>			
</div>

