<html lang="en"><head>
 <head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

  <?php echo $this->headMeta()
  ->appendName('viewport', 'width=device-width, initial-scale=1.0')
  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <!-- Le styles -->
  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
  ->prependStylesheet($this->basePath() . '/css/style.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
  ->prependStylesheet($this->basePath() . '//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>


  <!-- Scripts -->
  <?php echo $this->headScript()
  ->prependFile($this->basePath() . '/js/custom.js')
  ->prependFile($this->basePath() . '/js/bootstrap-datetimepicker.min.js')
  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
  ->prependFile($this->basePath() . '/js/jquery.min.js')
  ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
  ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
  ; ?>

<style type="text/css">
  .form-horizontal 
  {
    padding-left: 15px;
    padding-right: 15px;
  }
</style>
</head>


<body style="">

             <?php echo $this->content; ?>
             

</body></html>