<?php echo $this->doctype(); ?>
<html lang="en">
<head>
  <meta charset="utf-8">
  <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>
  <?php echo $this->headMeta()
  ->appendName('viewport', 'width=device-width, initial-scale=1.0')
  ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
  ?>

  <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
  ->prependStylesheet($this->basePath() . '/css/bootstrap-switch.css')
  ->prependStylesheet($this->basePath() . '/css/style.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap-datetimepicker.min.css')
  ->prependStylesheet($this->basePath() . '//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
  ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') 
  ->prependStylesheet($this->basePath() . '/datetimepicker/jquery.datetimepicker.css')
  ?>

  <?php echo $this->headScript()
  ->prependFile($this->basePath() . '/js/custom.js')
  ->prependFile($this->basePath() . '/js/bootstrap-switch.min.js')
  ->prependFile($this->basePath() . '/js/bootstrap.js')
  ->prependFile($this->basePath() . '/js/jquery.min.js')
  ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
  ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
  ; ?>

  <link href='calendar/fullcalendar/bootstrap-timepicker.min.css' rel='stylesheet' media='print' />
  <link href='calendar/fullcalendar/custom.css' rel='stylesheet' />
  <link href='calendar/fullcalendar/fullcalendar.css' rel='stylesheet' />
  <link href='calendar/fullcalendar/fullcalendar.print.css' rel='stylesheet' media='print' />
  <script src='calendar/lib/jquery.min.js'></script>
  <script src='calendar/lib/jquery-ui.custom.min.js'></script>
  <script src='calendar/fullcalendar/fullcalendar.js'></script>
  <link rel="stylesheet" href="http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" />
  <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  <script src="calendar/lib/bootstrap-timepicker.js"></script>
  <script src="/js/bootstrap.min.js"></script>
  <script src='/datetimepicker/jquery.datetimepicker.js'></script>
</head>
<body>
  <div class="navbar navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
      <div class="navbar-header">
        <button class="navbar-toggle btn-navbar" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
          <span>Menu</span>
        </button>
        <a href="index.html" class="navbar-brand hidden-lg">  Event planner</a>
      </div>
      <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">         
        <ul class="nav navbar-nav">  
          <li class="dropdown dropdown-big">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="label label-success"><i class="icon-cloud-upload"></i></span> Download events</a>
            <ul class="dropdown-menu">
              <li>
                <p>Photo Upload in Progress</p>
                <div class="progress progress-striped active">
                  <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
                    <span class="sr-only">40% Complete</span>
                  </div>
                </div>
                <hr>
                <p>Video Upload in Progress</p>
                <div class="progress progress-striped active">
                  <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%">
                    <span class="sr-only">80% Complete</span>
                  </div>
                </div> 
                <hr>             
                <div class="drop-foot">
                  <a href="#">View All</a>
                </div>
              </li>
            </ul>
          </li>
          <li class="dropdown dropdown-big">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span class="label label-danger"><i class="icon-refresh"></i></span> Refresh events</a>
            <ul class="dropdown-menu">
              <li>
                <p><span class="label label-info"><i class="icon-cloud"></i></span> Syncing Members Lists to Server</p>
                <hr>
                <p><span class="label label-warning"><i class="icon-cloud"></i></span> Syncing Bookmarks Lists to Cloud</p>
                <hr>
                <div class="drop-foot">
                  <a href="#">View All</a>
                </div>
              </li>
            </ul>
          </li>
        </ul>
        <form class="navbar-form navbar-left" role="search">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Search">
          </div>
        </form>
        <ul class="nav navbar-nav pull-right">
          <li class="dropdown pull-right">            
            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
              <i class="icon-user"></i> Admin <b class="caret"></b>              
            </a>
            <ul class="dropdown-menu">
              <li><a href="/user"><i class="icon-user"></i> Profile</a></li>
              <li><a href="/user/changeEmail"><i class="icon-cogs"></i> Settings</a></li>
              <li><a href="/user/logout"><i class="icon-off"></i> Logout</a></li>
            </ul>
          </li>
        </ul>
      </nav>
    </div>
  </div>
</div>
<header>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="logo">
          <h1><a href="#"><span class="bold">Event Planner</span></a></h1>
          <p class="meta">test</p>
        </div>
      </div>
      <div class="col-md-4">
        <ul class="nav nav-pills">
          <li class="dropdown dropdown-big">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
              <i class="icon-comments"></i> Chats <span class="label label-info">6</span> 
            </a>
            <ul class="dropdown-menu">
              <li>
                <h5><i class="icon-comments"></i> Chats</h5>
                <hr>
              </li>
              <li>
                <h6><a href="#">Hi :)</a> <span class="label label-warning pull-right">10:42</span></h6>
                <div class="clearfix"></div>
                <hr>
              </li>
              <li>
                <h6><a href="#">How are you?</a> <span class="label label-warning pull-right">20:42</span></h6>
                <div class="clearfix"></div>
                <hr>
              </li>
              <li>
                <h6><a href="#">What are you doing?</a> <span class="label label-warning pull-right">14:42</span></h6>
                <div class="clearfix"></div>
                <hr>
              </li>                  
              <li>
                <div class="drop-foot">
                  <a href="#">View All</a>
                </div>
              </li>                                    
            </ul>
          </li>
          <li class="dropdown dropdown-big">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
              <i class="icon-envelope-alt"></i> Inbox <span class="label label-primary">6</span> 
            </a>
            <ul class="dropdown-menu">
              <li>
                <h5><i class="icon-envelope-alt"></i> Messages</h5>
                <hr>
              </li>
              <li>
                <h6><a href="#">Hello how are you?</a></h6>
                <p>Quisque eu consectetur erat eget  semper...</p>
                <hr>
              </li>
              <li>
                <h6><a href="#">Today is wonderful?</a></h6>
                <p>Quisque eu consectetur erat eget  semper...</p>
                <hr>
              </li>
              <li>
                <div class="drop-foot">
                  <a href="#">View All</a>
                </div>
              </li>                                    
            </ul>
          </li>
          <li class="dropdown dropdown-big">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
              <i class="icon-user"></i> Users <span class="label label-success">6</span> 
            </a>
            <ul class="dropdown-menu">
              <li>
                <h5><i class="icon-user"></i> Users</h5>
                <hr>
              </li>
              <li>
                <h6><a href="#">Ravi Kumar</a> <span class="label label-warning pull-right">Free</span></h6>
                <div class="clearfix"></div>
                <hr>
              </li>
              <li>
                <h6><a href="#">Balaji</a> <span class="label label-important pull-right">Premium</span></h6>
                <div class="clearfix"></div>
                <hr>
              </li>
              <li>
                <h6><a href="#">Kumarasamy</a> <span class="label label-warning pull-right">Free</span></h6>
                <div class="clearfix"></div>
                <hr>
              </li>                  
              <li>
                <div class="drop-foot">
                  <a href="#">View All</a>
                </div>
              </li>                                    
            </ul>
          </li> 
        </ul>
      </div>
      <div class="col-md-4">
        <div class="header-data">
          <div class="hdata">
            <div class="mcol-left">
              <i class="icon-signal bred"></i> 
            </div>
            <div class="mcol-right">
              <p><a href="#">0</a> <em>Invitations</em></p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="hdata">
            <div class="mcol-left">
              <i class="icon-user bblue"></i> 
            </div>
            <div class="mcol-right">
              <p><a id="friends" href="#"></a> <em>Friends</em></p>
            </div>
            <div class="clearfix"></div>
          </div>
          <div class="hdata">
            <div class="mcol-left">
              <i class="icon-money bgreen"></i> 
            </div>
            <div class="mcol-right">
              <p><a href="#">0</a><em>Credits</em></p>
            </div>
            <div class="clearfix"></div>
          </div>                        
        </div>
      </div>
    </div>
  </div>
</header>
<div class="content">
  <div class="sidebar">
    <div class="sidebar-dropdown"><a href="#">Navigation</a></div>
    <ul id="nav">
      <li><a href="/user" ><i class="icon-home"></i> Dashboard</a>           
        <li><a href="/social"><i class="icon-bar-chart"></i> Members</a></li> 
        <li><a href="/social/groups"><i class="icon-bar-chart"></i> Groups</a></li> 
        <li><a href="/calender"><i class="icon-calendar"></i> Calendar</a></li>
        <li><a href="/user/admin"><i class="icon-tasks"></i> Admin</a></li>
      </ul>
    </div>
    <div class="mainbar">
      <div class="matter">
        <div class="container">
          <?php echo $this->content; ?>
        </div>
      </div>
    </div> 
  </div>
  <?php echo $this->inlineScript() ?>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <p class="copy">Copyright © 2013 | <a href="#">McNolia</a> </p>
        </div>
      </div>
    </div>
  </footer>
  <span class="totop" style="display: block;"><a href="#"><i class="icon-chevron-up"></i></a></span>
  <div id="myModal" class="modal fade in myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close sluit" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
        <div class="padd">
          <form method="post" id="eventForm" action="">
            <div class="input-group">
              <div class="col-sm-9">
                <label class="control-label no-padding-right">Eventname</label>
                <input type="text" name="title" maxlength="200" id="id_name" class="form-control">
              </div>
            </div>
            <br>
            <div class="input-group">
              <div class="col-sm-9">
                <p id="datepairExample">
                  <label class="control-label no-padding-right">Event start</label>
                  <input type="text" name="start" id="id_eventstart" class="form-control date start datetimepicker">
                  <br>
                </p>
              </div>
            </div>
            <br>
            <div class="input-group">
              <div class="col-sm-9">
                <label class="control-label no-padding-right">Event duration</label>
                <input type="text" readonly="" name="end" id="id_eventend" class="form-control date start">
                <select class="form-control duration">
                  <option value="0.5">+ 0.5 Hour</option>
                  <option value="1">+ 1.0 Hour</option>
                  <option value="1.5">+ 1.5 Hour</option>
                  <option value="2">+ 2.0 Hour</option>
                  <option value="2.5">+ 2.5 Hour</option>
                  <option value="3">+ 3.0 Hour</option>
                  <option value="3.5">+ 3.5 Hour</option>
                  <option value="4">+ 4.0 Hour</option>
                  <option value="4.5">+ 4.5 Hour</option>
                  <option value="5">+ 5.0 Hour</option>
                  <option value="5.5">+ 5.5 Hour</option>
                  <option value="6">+ 6.0 Hour</option>
                  <option value="6.5">+ 6.5 Hour</option>
                  <option value="7">+ 7.0 Hour</option>
                </select>  
              </div>
            </div>
            <br>
            <div class="input-group">
              <div class="col-sm-9">
                <label class="control-label no-padding-right">Capacity</label>
                <input type="number" name="capacity" id="id_capacity" class="form-control ">            
              </div>
              <br>
              <div class="input-group">
              <div class="col-sm-9">
                
              </div>
            </div>
            </div>               
          
        </div>
        <div class="modal-footer">
        <input type="submit" class="btn btn-default" value="Submit">
        </form>
        </div>
      </div>
    </div>
  </div>
</body>
</html>
